export enum Features {
    SORTING_LIST = "SORTING_LIST",
    ASC = "ASC",
    DESC = "DESC",

    OR = "OR",
    AND = "AND",
    LT = "LT",
    GT = "GT",
    LE = "LE",
    GE = "GE",
    NEQ = "NEQ",
    EQ = "EQ",

    CONTAINS = "CONTAINS",
    CONTAINS_WORD = "CONTAINS_WORD",
    STARTS_WITH = "STARTS_WITH",
    ENDS_WITH = "ENDS_WITH",

    ADDITION = "ADDITION",
    SUBTRACTION = "SUBTRACTION",
    MULTIPLICATION = "MULTIPLICATION",
    DIVISION = "DIVISION",

    PARENTHESES = "PARENTHESES",
    IDENTIFIER_PATH = "IDENTIFIER_PATH",
    IDENTIFIER = "IDENTIFIER",
    BOOLEAN = "BOOLEAN",
    NUMBER = "NUMBER",
    STRING = "STRING",

    FUNCTION_CALL = "FUNCTION_CALL",
}